### ISSUE TITLE
AuthManager::removeAll() fails to reset FOREIGN_KEY_CHECKS

### ISSUE THREAD

**Issue by Dragonrun1** [potievdev/slim-rbac#11]
So in the AuthManager::removeAll() in the SQL it sets FOREIGN_KEY_CHECKS off with a 0 on line 48 then does all the table TRUNCATEs followed by once again set FOREIGN_KEY_CHECKS=0 instead of FOREIGN_KEY_CHECKS=1. Sure it's just a C&P error but surprised no one else has noticed it.

**Comment by potievdev** [comment]
Thank you for your contrubution. It is realy C&P error. I will fix it as soon as possible. Also you can send pull request)

**Comment by potievdev** [comment]
Bug fixed
